- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend/
    state: directory

- copy:
    src: ~/project/backend/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: ~/project/backend/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i
- name: Start the app
  shell: |
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations
    export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js}
    export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts
    export TYPEORM_HOST=database-2.crbwodtfpbf0.us-east-1.rds.amazonaws.com
    export TYPEORM_PORT=5432
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=postgres
    export TYPEORM_DATABASE=postgres

    pm2 stop default
    pm2 start -f /home/ubuntu/backend/dist/main.js